def exceptionhandling():
  try:
    num=10
    num1=20
    num2=10
    division=(num+num1)/num2
    print(division)
  except:
      print("there is a exception")
  else:
      print("there is no problem") 
exceptionhandling()
